apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: muchtodo
data:
  PORT: "8080"
  DB_NAME: "much_todo_db"

  MONGO_URI: "mongodb://admin:password@mongodb:27017/much_todo_db?authSource=admin"

  ENABLE_CACHE: "false"

  JWT_EXPIRATION_HOURS: "72"

  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
